Add PAYEER payment gateway
FOSSBilling/extension-directory pull request #161
Opened 2024-06-21 23:03 UTC by neto737

Add PAYEER payment gateway

https://github.com/neto737/PAYEER-FOSSBilling

2024-06-22 11:28 UTC, ChristianGabs requested changes

2024-06-23 11:52 UTC, jaapmarcus approved these changes

2024-06-24 13:47 UTC, ChristianGabs commented on data/extensions.ts
>          "https://github.com/neto737/PAYEER-FOSSBilling/releases/download/0.1.0/PAYEER.zip",
Change this to 0.1.1 as they will download the old version

2024-06-24 13:49 UTC, ChristianGabs commented on data/extensions.ts
> +    version: "0.1.0",
Same here, migrate to 0.1.1

2024-06-25 02:56 UTC, merged

2024-06-25 02:56 UTC, BelleNottelling commented
Thanks!